name: tf_serving_ztdl
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - pip:
    - flask
    - flask-cors
    - grpcio
    - grpcio-tools
    - keras
    - h5py
    - tensorflow
    - gunicorn

